FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY ./requirements-frontend.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements-frontend.txt

# Copy the application code
COPY ./src .

# Command to run the application
CMD ["streamlit", "run", "src/frontend.py", "--server.port=5000"]